### ISSUE TITLE
Failed to load source for dependency

### ISSUE THREAD

**Issue by fuzious** [sslab-gatech/Rudra#15] opened 2021-09-20 17:57 UTC
![image](https://user-images.githubusercontent.com/42795731/134050220-f4ad4937-b01e-4a3d-9f00-9226649ca642.png)

I was trying to run rudra for [this](https://github.com/trustfractal/protocol/tree/331a426a3d48ea985ab45614e1c9dffc305240aa/blockchain/pallets/minting) but it gives the above error, how to resolve this

**Comment by Qwaz** [comment] 2021-09-20 18:59
Duplicate of #13. Please check [this comment](https://github.com/sslab-gatech/Rudra/issues/13#issuecomment-912590709) in the thread.

**Closed by Qwaz** 2021-09-20 18:59 UTC
