### ISSUE TITLE
Update to latest rust version

### ISSUE THREAD

**Issue by Bergmann89** [sslab-gatech/Rudra#53] opened 2023-04-21 09:51 UTC
Hey there,

are there any plans to update rudra to the latest rust compiler? Would like to use this on my project :)

Greetings, Bergmann89.

**Comment by 8573** [comment] 2023-04-21 19:59
I think this is a duplicate of #51.

**Comment by eslerm** [comment] 2023-04-21 21:04
Most related discussion is in https://github.com/sslab-gatech/Rudra/issues/19

**Comment by Qwaz** [comment] 2023-04-22 16:05
Closing as duplicate

**Closed by Qwaz** 2023-04-22 16:05 UTC
